version: '3.0'
services:
  db:
    image: mysql
    restart: always
    volumes:
      - ./mysqli:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./web/:/var/www/html/:cached
      - ./log-4.txt:/var/www/log-4.txt
    ports:
      - "80:80"
